#mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
 # type-aliases-package: com.atguigu.springcloud.entities  #所有entity别名类所在包
 # mapper-locations: classpath:mapper/*.xml  #mapper映射文件
info:
  say: hello myconfig update version 6
#spring:
#  application:
 #   name: cloud-config-client-nobootstrap1
eureka:
  instance:
    prefer-ip-address: true #eureka主页列表中显示具体ip地址和端口
