mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities  #所有entity别名类所在包
  mapper-locations: classpath:mapper/*.xml  #mapper映射文件